baseURL = 'https://samyou.xyz'
languageCode = 'en-us'
title = 'Sam You'
theme = 'nostyleplease'

[caches]
[caches.images]
dir = ':cacheDir/images'

# this can be improved
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  favicon = '/favicon.ico'

[services]
  [services.googleAnalytics]
    id = 'G-PVKTQ6B49X'